import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Theme from '../app/providers/themeProvider';
import Navbar from '../app/layouts/navbar/navbar';
import RenderSidebar from '../app/layouts/conditionallyRenderSidebars/renderSidebar';
import { VisibilityContextProvider } from '../app/context/visibility.context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'YouTube-clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <VisibilityContextProvider>
          <Theme>
            <Navbar />
            <RenderSidebar />
            {children}
          </Theme>
        </VisibilityContextProvider>
      </body>
    </html>
  );
}
